on:
  push:
    branches: [master, develop, tour-embedding]

env:
  NODE_VERSION: 18.4.0

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      SCRIPT_FILENAME: ${{ steps.set-script-filename.outputs.SCRIPT_FILENAME }}
      MINIFIED_SCRIPT_FILENAME: ${{ steps.set-minified-script-filename.outputs.MINIFIED_SCRIPT_FILENAME }}
    steps:
      - uses: actions/checkout@v3
      - id: set-script-filename
        run: echo "SCRIPT_FILENAME=${{ github.ref_name == 'master' && 'tourbuilder.js' || 'tourbuilder.dev.js' }}" >> $GITHUB_OUTPUT
      - id: set-minified-script-filename
        run: echo "MINIFIED_SCRIPT_FILENAME=${{ github.ref_name == 'master' && 'tourbuilder.min.js' || 'tourbuilder.dev.min.js' }}" >> $GITHUB_OUTPUT
  cd:
    needs: [params]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build dist
        run: npm run build -- --file dist/${{ needs.params.MINIFIED_SCRIPT_FILENAME }}
      - name: Deploy to public s3
        run: |
          aws s3 cp dist/${{ needs.params.MINIFIED_SCRIPT_FILENAME }} s3://${{ vars.AWS_BUCKET_NAME }}/scripts/
          aws s3 cp tourbuilder.js s3://${{ vars.AWS_BUCKET_NAME }}/scripts/{{ needs.params.SCRIPT_FILENAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CDN_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Clear CDN Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CDN_API_ZONE_IDENTIFIER }}/purge_cache" \
            -H "X-Auth-Email: ${{ secrets.CDN_API_AUTH_EMAIL }}" \
            -H "Authorization: Bearer ${{ secrets.CDN_API_AUTH_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://static.tourbuilder.com/scripts/${{ needs.params.SCRIPT_FILENAME }}", "https://static.tourbuilder.com/scripts/${{ needs.params.MINIFIED_SCRIPT_FILENAME }}"]}'
