on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  NODE_VERSION: 18.4.0

jobs:
  integration:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Start http server
        run: |
          npx http-server www &
          HTTP_SERVER_PID=$!
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          wait-on: "http://localhost:8080"
      - name: Stop http server
        if: always()
        run: kill $HTTP_SERVER_PID
