on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  NODE_VERSION: 20.12.2
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build scripts
        run: |
          npx esbuild tourbuilder.js --bundle --outfile=dist/tourbuilder.js
          npx esbuild tourbuilder.js --bundle --minify --outfile=dist/tourbuilder.min.js
      - name: Start http server
        run: |
          npx http-server www &
          HTTP_SERVER_PID=$!
          echo $HTTP_SERVER_PID
      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          wait-on: "http://localhost:8080"
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Stop http server
        if: always()
        run: |
          echo $HTTP_SERVER_PID
          kill $HTTP_SERVER_PID
